ttpmacro_path = 'C:\Program Files (x86)\teraterm\ttpmacro.exe'
server_data_api = 'http://rp.local:3000/server'
user_data_api = 'http://rp.local:3000/user'
default_login_user = 'login00'
default_login_su = 'root'
default_login_win = 'tv'
default_login_oc_url = 'https://example.com'
default_login_oc_user = '[sid]ope'
default_login_oc_id = 'AAA_[sid]ope_aaa'